# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
sudo: true
warnings_are_errors: true

# work around temporary travis + R 3.5 bug
r_packages: devtools
